spring:
  application:
    name: MSTxFleet-Trip
  cloud:
    discovery:
      enabled: false
  kafka:
    #bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


service:
  postgis:
    name: MSTXFLEET-DBS-POSTGIS
    url: mstxfleet-api-gateway:8888/MSTXFLEET-DBS-POSTGIS
  redis:
    name: MSTXFLEET-DBS-REDIS
    url: mstxfleet-api-gateway:8888/MSTXFLEET-DBS-REDIS
