spring:
  application:
    name: MSTxFleet-Trip
  cloud:
    discovery:
      enabled: false


service:
  postgis:
    name: MSTXFLEET-DBS-POSTGIS
    url: mstxfleet-api-gateway:8888/MSTXFLEET-DBS-POSTGIS